name: first-challenge

on: push

jobs:
  windows-job: 
    runs-on: windows-latest
    steps:
      - run: date

  mac-job: 
    runs-on: macos-latest
    steps:
      - run: date

  ubuntu2-job: 
    runs-on: macos-latest
    needs: [windows-job, mac-job]
    steps:
      - run: date