name: first-challenge

on: push

jobs:
  ubuntu-job: 
    runs-on: ubuntu-lastest
    steps:
      - run: date

  windows-job: 
    runs-on: windows-latest
    steps:
      - run: date

  mac-job: 
    runs-on: macos-latest
    steps:
      - run: date

  ubuntu2-job: 
    runs-on: ubuntu-latest
    depends-on: [windows-job, ubuntu-job, mac-job]
    steps:
      - run: date